python gen_watermarks.py --dataset cifar10 --num_classes 10 --arch resnet34 --method ProtectingIP --wm_type noise --save_wm --runname cifar10_resnet34_noise_C10_K20_Full-Entropy --coding Full-Entropy --K 20 --trg_set_size 400 --cuda cuda:2
python gen_watermarks.py --dataset cifar10 --num_classes 10 --arch resnet34 --method ProtectingIP --wm_type noise --save_wm --runname cifar10_resnet34_noise_C10_K20_Tardos-1 --coding Tardos-1 --K 20 --trg_set_size 400 --cuda cuda:2
python gen_watermarks.py --dataset cifar10 --num_classes 10 --arch resnet34 --method ProtectingIP --wm_type noise --save_wm --runname cifar10_resnet34_noise_C10_K20_Tardos-2 --coding Tardos-2 --K 20 --trg_set_size 400 --cuda cuda:2
python gen_watermarks.py --dataset cifar10 --num_classes 10 --arch resnet34 --method ExponentialWeighting --save_wm --runname cifar10_resnet34_exponential-weighting_C10_K20_Full-Entropy --coding Full-Entropy --K 20 --trg_set_size 400 --cuda cuda:2
python gen_watermarks.py --dataset cifar10 --num_classes 10 --arch resnet34 --method ExponentialWeighting --save_wm --runname cifar10_resnet34_exponential-weighting_C10_K20_Tardos-1 --coding Tardos-1 --K 20 --trg_set_size 400 --cuda cuda:2
python gen_watermarks.py --dataset cifar10 --num_classes 10 --arch resnet34 --method ExponentialWeighting --save_wm --runname cifar10_resnet34_exponential-weighting_C10_K20_Tardos-2 --coding Tardos-2 --K 20 --trg_set_size 400 --cuda cuda:2
python gen_watermarks.py --dataset cifar10 --num_classes 10 --arch resnet34 --method Ood --save_wm --runname cifar10_resnet34_ood_C10_K20_Full-Entropy --coding Full-Entropy --K 20 --trg_set_size 400 --cuda cuda:2
python gen_watermarks.py --dataset cifar10 --num_classes 10 --arch resnet34 --method Ood --save_wm --runname cifar10_resnet34_ood_C10_K20_Tardos-1 --coding Tardos-1 --K 20 --trg_set_size 400 --cuda cuda:2
python gen_watermarks.py --dataset cifar10 --num_classes 10 --arch resnet34 --method Ood --save_wm --runname cifar10_resnet34_ood_C10_K20_Tardos-2 --coding Tardos-2 --K 20 --trg_set_size 400 --cuda cuda:2
