python train_wo_wm.py --dataset cifar10 --num_classes 10 --arch resnet34 --epochs_wo_wm 60 --batch_size 64 --lr 0.1 --sched MultiStepLR_cifar10 --runname cifar10_resnet34_clean --cuda cuda:2
python train_wo_wm.py --dataset cinic10 --num_classes 10 --arch resnet34 --epochs_wo_wm 60 --batch_size 64 --lr 0.1 --sched MultiStepLR_cifar10 --runname cinic10_resnet34_clean --cuda cuda:2

python gen_watermarks.py --dataset cifar10 --num_classes 10 --arch resnet34 --method ProtectingIP --wm_type noise --save_wm --runname cifar10_resnet34_noise_C10_K10_Full-Entropy --coding Full-Entropy --K 10 --trg_set_size 400 --cuda cuda:2
python gen_watermarks.py --dataset cifar10 --num_classes 10 --arch resnet34 --method ProtectingIP --wm_type noise --save_wm --runname cifar10_resnet34_noise_C10_K10_Tardos-1 --coding Tardos-1 --K 10 --trg_set_size 400 --cuda cuda:2
python gen_watermarks.py --dataset cifar10 --num_classes 10 --arch resnet34 --method ProtectingIP --wm_type noise --save_wm --runname cifar10_resnet34_noise_C10_K10_Tardos-2 --coding Tardos-2 --K 10 --trg_set_size 400 --cuda cuda:2
python gen_watermarks.py --dataset cifar10 --num_classes 10 --arch resnet34 --method ExponentialWeighting --save_wm --runname cifar10_resnet34_exponential-weighting_C10_K10_Full-Entropy --coding Full-Entropy --K 10 --trg_set_size 400 --cuda cuda:2
python gen_watermarks.py --dataset cifar10 --num_classes 10 --arch resnet34 --method ExponentialWeighting --save_wm --runname cifar10_resnet34_exponential-weighting_C10_K10_Tardos-1 --coding Tardos-1 --K 10 --trg_set_size 400 --cuda cuda:2
python gen_watermarks.py --dataset cifar10 --num_classes 10 --arch resnet34 --method ExponentialWeighting --save_wm --runname cifar10_resnet34_exponential-weighting_C10_K10_Tardos-2 --coding Tardos-2 --K 10 --trg_set_size 400 --cuda cuda:2
python gen_watermarks.py --dataset cifar10 --num_classes 10 --arch resnet34 --method Ood --save_wm --runname cifar10_resnet34_ood_C10_K10_Full-Entropy --coding Full-Entropy --K 10 --trg_set_size 400 --cuda cuda:2
python gen_watermarks.py --dataset cifar10 --num_classes 10 --arch resnet34 --method Ood --save_wm --runname cifar10_resnet34_ood_C10_K10_Tardos-1 --coding Tardos-1 --K 10 --trg_set_size 400 --cuda cuda:2
python gen_watermarks.py --dataset cifar10 --num_classes 10 --arch resnet34 --method Ood --save_wm --runname cifar10_resnet34_ood_C10_K10_Tardos-2 --coding Tardos-2 --K 10 --trg_set_size 400 --cuda cuda:2

python embed_watermarks.py --method ProtectingIP --embed_type pretrained --wm_type noise --loadmodel cifar100_resnet34_clean --dataset cifar100 --num_classes 100 --arch resnet34 --epochs_w_wm 20 --batch_size 64 --wm_batch_size 16 --lr 0.0001 --optim SGD --sched CosineAnnealingLR --patience 20 --runname cifar100_resnet34_noise_N1_0 --trg_set_sizes_list 37 --cuda cuda:2
python embed_watermarks.py --method FrontierStitching --embed_type pretrained --loadmodel cifar100_resnet34_clean --dataset cifar100 --num_classes 100 --arch resnet34 --epochs_w_wm 20 --batch_size 64 --wm_batch_size 16 --lr 0.0001 --optim SGD --sched CosineAnnealingLR --patience 20 --runname cifar100_resnet34_frontier-stitching_N1_0 --trg_set_sizes_list 37 --cuda cuda:2
python embed_watermarks.py --method ExponentialWeighting --embed_type pretrained --loadmodel cifar100_resnet34_clean --dataset cifar100 --num_classes 100 --arch resnet34 --epochs_w_wm 20 --batch_size 64 --wm_batch_size 16 --lr 0.0001 --optim SGD --sched CosineAnnealingLR --patience 20 --runname cifar100_resnet34_exponential-weighting_N1_0 --trg_set_sizes_list 37 --cuda cuda:2